/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.FileOperationsHandler;
import Control.InvoiceOperationsHandler;
import Model.Invoice;
import Model.InvoiceItem;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    Map<Integer, Invoice> invoices;

    public MainForm() {
        initComponents();

        invoices = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lbl_InvoiceNo = new javax.swing.JLabel();
        lbl_InvoiceTotal = new javax.swing.JLabel();
        txt_Date = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        btn_NewInvoice = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        btn_NewLine = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        MenuItem_load = new javax.swing.JMenuItem();
        MenuItem_save = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales invoice generator");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Date", "Customer", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Invoices Table");

        jLabel2.setText("Invoice Number");

        jLabel3.setText("Invoice Date");

        jLabel4.setText("Customer Name");

        jLabel5.setText("Invoice Total");

        jLabel6.setText("Invoice Items");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Item Name", "Item Price", "Count", "Item Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable2);

        lbl_InvoiceNo.setText("0");

        lbl_InvoiceTotal.setText("0");

        btn_NewInvoice.setText("Create New Invoice");
        btn_NewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewInvoiceActionPerformed(evt);
            }
        });

        btn_Delete.setText("Delete Invoice");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        btn_NewLine.setText("Add new line");
        btn_NewLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewLineActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        MenuItem_load.setText("Load File");
        MenuItem_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_loadActionPerformed(evt);
            }
        });
        fileMenu.add(MenuItem_load);

        MenuItem_save.setText("Save File");
        MenuItem_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_saveActionPerformed(evt);
            }
        });
        fileMenu.add(MenuItem_save);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_InvoiceTotal)
                                    .addComponent(lbl_InvoiceNo))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Date)
                            .addComponent(txt_name))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btn_NewInvoice)
                .addGap(69, 69, 69)
                .addComponent(btn_Delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_NewLine)
                .addGap(78, 78, 78)
                .addComponent(btn_Save)
                .addGap(91, 91, 91)
                .addComponent(btn_Cancel)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl_InvoiceNo))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_InvoiceTotal))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_NewInvoice)
                    .addComponent(btn_Delete)
                    .addComponent(btn_Save)
                    .addComponent(btn_Cancel)
                    .addComponent(btn_NewLine))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_loadActionPerformed
        // TODO add your handling code here:
        invoices.clear();
        FileOperationsHandler.loadFiles(invoices);
        for (Invoice invoice : invoices.values()) {
            invoice.calculateInvoiceTotal();
        }
        clearForm();
        InvoiceOperationsHandler.loadDataIntoInvoicesTable(invoices, jTable1);
    }//GEN-LAST:event_MenuItem_loadActionPerformed

    private void MenuItem_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_saveActionPerformed
        // TODO add your handling code here:
        FileOperationsHandler.saveFiles(invoices);
        JOptionPane.showMessageDialog(null, "The data have been saved to the respective files successfully","Success",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_MenuItem_saveActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        loadSelectedRowIntoForm((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
    }//GEN-LAST:event_jTable1MouseReleased

    private void btn_NewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewInvoiceActionPerformed
        // TODO add your handling code here:
        InvoiceOperationsHandler.createInvoice(invoices, jTable1);
    }//GEN-LAST:event_btn_NewInvoiceActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        int key = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        InvoiceOperationsHandler.deleteSelectedInvoice(jTable1, invoices, key);
        clearForm();
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_NewLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewLineActionPerformed
        // TODO add your handling code here:
        int key = Integer.parseInt(lbl_InvoiceNo.getText());
        InvoiceOperationsHandler.createItem(jTable2, key);
    }//GEN-LAST:event_btn_NewLineActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to save the updates?", "Warning", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            
            SimpleDateFormat format = new SimpleDateFormat("dd-mm-yyyy");
            format.setLenient(false);
            try {
                Date tmp = format.parse(txt_Date.getText());

                int key = Integer.parseInt(lbl_InvoiceNo.getText());
                String date = txt_Date.getText();
                String name = txt_name.getText();
                ArrayList<InvoiceItem> items = new ArrayList<>();
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                for (int i = 0; i < model.getRowCount(); i++) {
                    String Itemname = String.valueOf(jTable2.getValueAt(i, 1));
                    double Itemprice = Double.parseDouble(String.valueOf(jTable2.getValueAt(i, 2)));
                    int count = Integer.parseInt(String.valueOf(jTable2.getValueAt(i, 3)));
                    InvoiceItem item = new InvoiceItem(key, Itemname, Itemprice, count);
                    items.add(item);
                    Object o = new Object();
                    o = item.getTotal();
                    jTable2.setValueAt(o, i, 4);
                }
                invoices.get(key).setCustomerName(name);
                invoices.get(key).setInvoiceDate(date);
                invoices.get(key).setInvoiceItems(items);
                invoices.get(key).calculateInvoiceTotal();
                lbl_InvoiceTotal.setText(String.valueOf(invoices.get(key).getInvoiceTotal()));
                InvoiceOperationsHandler.loadDataIntoInvoicesTable(invoices, jTable1);
                JOptionPane.showMessageDialog(null, "Updates saved successfully", "", JOptionPane.INFORMATION_MESSAGE);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Wrong date format", "ERROR!!", JOptionPane.ERROR_MESSAGE);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please complete the invoice data", "ERROR!!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to revert the unsaved updates?", "Warning", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            loadSelectedRowIntoForm(Integer.parseInt(lbl_InvoiceNo.getText()));
        }
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void loadSelectedRowIntoForm(int key) {
        Invoice invoice = invoices.get(key);
        lbl_InvoiceNo.setText(String.valueOf(invoice.getInvoiceNumber()));
        txt_name.setText(invoice.getCustomerName());
        txt_Date.setText(invoice.getInvoiceDate());
        lbl_InvoiceTotal.setText(String.valueOf(invoice.getInvoiceTotal()));

        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        tableModel.setRowCount(0);
        Object rowData[] = new Object[5];
        for (InvoiceItem item : invoice.getInvoiceItems()) {
            rowData[0] = item.getInvoiceNum();
            rowData[1] = item.getName();
            rowData[2] = item.getPrice();
            rowData[3] = item.getCount();
            rowData[4] = item.getTotal();
            tableModel.addRow(rowData);
        }

    }

    private void clearForm() {
        lbl_InvoiceNo.setText("0");
        txt_name.setText("");
        txt_Date.setText("");
        lbl_InvoiceTotal.setText("0");
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        tableModel.setRowCount(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem_load;
    private javax.swing.JMenuItem MenuItem_save;
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_NewInvoice;
    private javax.swing.JButton btn_NewLine;
    private javax.swing.JButton btn_Save;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_InvoiceNo;
    private javax.swing.JLabel lbl_InvoiceTotal;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
